export var allSongs = [
    "September - Earth, Wind & Fire",
    "Happy - Pharrell Williams",
    "Walking on Sunshine - Katrina & The Waves",
    "I’m Coming Out - Diana Ross",
    "Can’t Stop the Feeling! - Justin Timberlake",
    "Girls Just Want to Have Fun - Cyndi Lauper",
    "I Want to Dance with Somebody - Whitney Houston",
    "Shut Up and Dance - Walk the Moon",
    "Don’t Worry, Be Happy - Bobby McFerrin",
    "Feel Good Inc - Gorillaz",
    "Geronimo - Sheppard",
    "Thunder - Imagine Dragons",
    "Shake It - Metro Station",
    "Good Life - OneRepublic",
    "Get Lucky - Daft Punk",
    "Lovely Day - Bill Withers",
    "MMMBop - Hanson",
    "Sir Duke - Stevie Wonder",
    "Good Vibrations - The Beach Boys",
    "Shiny Happy People - REM",
    "Stay - Rihanna",
    "Small Bump - Ed Sheeran",
    "Buy the Stars - MARINA",
    "Old Money - Lana Del Rey",
    "I'll Never Love Again - Lady Gaga",
    "26 - Paramaore",
    "Stay - Miley Cyrus",
    "Lithium - Evanescence",
    "Ruby - Foster the People",
    "Everything I Wanted - Billie Eilish",
    "The Scientist - Coldplay",
    "Falling Short - Lapsley",
    "Look After You - The Fray",
    "Forever and Always - Taylor Swift",
    "A Little Bit Longer - Jonas Brothers",
    "Jar of Hearts - Christina Perri",
    "If I Ever Feel Better - Phoenix",
    "Ghostin - Ariana Grande",
    "You & I - One Durectuib",
    "Praying - Kesha",
    "Everybody Hurts - REM",
    ];